stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed/test_processed.csv
    - data/processed/train_processed.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed/test_processed.csv
    - data/processed/train_processed.csv
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features/test_tfid.csv
    - data/features/train_tfid.csv

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features/train_tfid.csv
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/label_encoder.pkl
    - models/model.pkl

  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/features/test_tfid.csv
    - models/label_encoder.pkl
    - models/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - metrics/eval.json:
        cache: false
